select P.PRODUCT_ID, P.PRODUCT_NAME, sum(P.PRICE * O.AMOUNT) as TOTAL_SALES
from FOOD_PRODUCT as P
join FOOD_ORDER as O on P.PRODUCT_ID = O.PRODUCT_ID
where Year(O.PRODUCE_DATE) = 2022 and Month(O.PRODUCE_DATE) = 5
group by P.PRODUCT_ID, P.PRODUCT_NAME
order by TOTAL_SALES desc, P.PRODUCT_ID asc